# Generated by Django 5.0.7 on 2025-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_provider_id',
            new_name='payment_provider_payment_id',
        ),
        migrations.AddField(
            model_name='rtorecord',
            name='cloudinary_urls',
            field=models.JSONField(default=list, help_text='Cloudinary document URLs'),
        ),
        migrations.AddField(
            model_name='rtorecord',
            name='gallery_html_url',
            field=models.URLField(blank=True, help_text='Netlify hosted gallery URL'),
        ),
    ]
